// <auto-generated />
namespace NewWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DodatnieWszystkichBudynkowFarmerskich : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodatnieWszystkichBudynkowFarmerskich));
        
        string IMigrationMetadata.Id
        {
            get { return "202009020744573_DodatnieWszystkichBudynkowFarmerskich"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
